# Generated by Django 3.2 on 2023-05-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_review_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
